const $=id=>document.getElementById(id);let manifest,stations=[],selected=0,cache={},latest={},chart,map;
const COLORS={pm1_ugm3:'#3f8f8b',pm25_ugm3:'#087d83',pm10_ugm3:'#ef8d43'};
function number(value){let n=Number(value);return value===''||value==null||!Number.isFinite(n)?null:n}
function csv(text){let lines=text.trim().split(/\r?\n/);if(lines.length<2)return[];let heads=lines.shift().split(',');return lines.filter(Boolean).map(line=>{let values=line.split(','),row={};heads.forEach((h,i)=>row[h]=values[i]??'');return row})}
function safeCsv(rows){let keys=Object.keys(rows[0]||{}),quote=v=>{let s=String(v??'');return /[",\n]/.test(s)?`"${s.replaceAll('"','""')}"`:s};return keys.join(',')+'\n'+rows.map(r=>keys.map(k=>quote(r[k])).join(',')).join('\n')}
function save(name,blob){let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function localDate(value){return new Date(value.replace(' ','T')).toLocaleString('es-CL')}
function isActive(station){return new Date(manifest.updated_at.replace(' ','T'))-new Date(station.last_at.replace(' ','T'))<48*3600e3}
function setupMap(){map=L.map('map',{scrollWheelZoom:false}).setView([-45.585,-72.09],11);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap'}).addTo(map);L.circle([-45.5712,-72.0683],{radius:6500,color:'#6ba8a4',weight:2,dashArray:'7 7',fillColor:'#82dfd1',fillOpacity:.12}).addTo(map).bindPopup('<b>Área general de Coyhaique</b><br>Ubicación individual no disponible para 13 sensores');let icon=L.divIcon({className:'',html:'<div style="width:22px;height:22px;border:5px solid white;border-radius:50%;background:#ef8d43;box-shadow:0 2px 9px #173b44"></div>',iconSize:[22,22],iconAnchor:[11,11]});L.marker([-45.61444,-72.10975],{icon}).addTo(map).bindPopup('<b>Sensores 31 y 39</b><br>Interior + exterior<br>278 m s. n. m.<br>−45.61444, −72.10975').openPopup()}
function filesFor(station,period){if(period==='all')return station.files;let days=period==='24h'?1:period==='7d'?7:30,base=new Date(manifest.updated_at.replace(' ','T')),cut=new Date(base-days*864e5);return station.files.filter(path=>{let m=path.match(/(\d{4})-(\d{2})\.csv$/);if(!m)return false;let start=new Date(+m[1],+m[2]-1,1),end=new Date(+m[1],+m[2],1);return end>=cut&&start<=base})}
async function rowsFor(station,period){let key=station.sensor_id+'|'+period;if(cache[key])return cache[key];let texts=await Promise.all(filesFor(station,period).map(path=>fetch(path+'?v='+encodeURIComponent(manifest.updated_at)).then(r=>{if(!r.ok)throw Error(`${r.status} ${path}`);return r.text()})));let rows=texts.flatMap(csv).sort((a,b)=>a.fecha.localeCompare(b.fecha));if(period!=='all'){let days=period==='24h'?1:period==='7d'?7:30,cut=new Date(manifest.updated_at.replace(' ','T')).getTime()-days*864e5;rows=rows.filter(r=>new Date(r.fecha.replace(' ','T')).getTime()>=cut)}return cache[key]=rows}
function daily(points){let groups={};points.forEach(point=>(groups[point.x.slice(0,10)]??=[]).push(point.y));let labels=Object.keys(groups).sort();return{labels,avg:labels.map(k=>groups[k].reduce((a,b)=>a+b,0)/groups[k].length),min:labels.map(k=>Math.min(...groups[k])),max:labels.map(k=>Math.max(...groups[k])),count:labels.map(k=>groups[k].length)}}
function chartData(points,period,color){if(period==='24h'||period==='7d')return{labels:points.map(p=>p.x),daily:false,datasets:[{label:'Lectura horaria',data:points.map(p=>p.y),borderColor:color,backgroundColor:color+'18',fill:true,pointRadius:points.length>170?0:2,tension:.18}]};let d=daily(points);return{labels:d.labels,daily:true,datasets:[{label:'Mínimo diario',data:d.min,borderColor:'transparent',pointRadius:0},{label:'Rango diario',data:d.max,borderColor:'transparent',backgroundColor:color+'2d',pointRadius:0,fill:'-1'},{label:'Promedio diario',data:d.avg,borderColor:color,backgroundColor:'transparent',borderWidth:2,pointRadius:d.avg.length>100?0:2,tension:.18}]}}
function normFor(allRows,key){let card=$('norm-card');card.className='';if(key==='pm1_ugm3'){return['Sin norma general','MP1 · valor observado sin clasificación','']};let points=allRows.map(r=>({x:r.fecha,y:number(r[key])})).filter(p=>p.y!==null),d=daily(points),today=manifest.updated_at.slice(0,10),eligible=d.labels.map((day,i)=>({day,value:d.avg[i],count:d.count[i]})).filter(x=>x.day<today&&x.count>=18),last=eligible.at(-1);if(!last)return['Datos insuficientes','Se requieren al menos 18 horas en un día',''];let limit=key==='pm25_ugm3'?50:130,reference=key==='pm25_ugm3'?'DS 12/2011':'DS 12/2021';let state=last.value<=limit?'Bajo referencia':'Sobre referencia',klass=last.value<=limit?'good':'bad';card.className=klass;return[state,`${last.value.toLocaleString('es-CL',{maximumFractionDigits:1})} µg/m³ · ${last.day} · ${reference}`,klass]}
function fillSensors(){let environment=$('environment').value,current=stations[selected]?.sensor_id,list=stations.filter(s=>environment==='all'||s.environment===environment);$('sensor').innerHTML=list.map(s=>`<option value="${s.sensor_id}">${isActive(s)?'●':'○'} Sensor ${s.sensor_id} · ${s.environment==='INDOOR'?'Interior':'Exterior'}</option>`).join('');let chosen=list.find(s=>s.sensor_id===current)||list.find(s=>s.sensor_id===(environment==='OUTDOOR'?39:31))||list[0];selected=stations.indexOf(chosen);$('sensor').value=chosen.sensor_id}
async function render(){let s=stations[selected],key=$('variable').value,period=$('period').value,variable=manifest.variables[key],color=COLORS[key];$('sensor-title').textContent=`Sensor ${s.sensor_id} · ${s.environment==='INDOOR'?'Interior':'Exterior'}`;$('sensor-context').textContent=s.location_precision==='exacta'?`${s.location} · ${s.altitude_m} m s. n. m.`:s.location;try{let rows=await rowsFor(s,period),normRows=period==='24h'?await rowsFor(s,'7d'):rows,points=rows.map(r=>({x:r.fecha,y:number(r[key])})).filter(p=>p.y!==null),last=latest[s.sensor_id],lastValue=number(last?.[key]),norm=normFor(normRows,key),display=chartData(points,period,color);$('last-value').textContent=lastValue===null||lastValue===undefined?'—':`${lastValue.toLocaleString('es-CL',{maximumFractionDigits:1})} ${variable.unit}`;$('last-time').textContent=last?localDate(last.fecha):'Sin lectura';$('norm-state').textContent=norm[0];$('norm-detail').textContent=norm[1];$('availability').textContent=points.length?'Con datos':'Sin datos recientes';$('record-count').textContent=`${points.length.toLocaleString('es-CL')} observaciones válidas`;$('chart-empty').hidden=!!points.length;$('chart-note').textContent=display.daily?'La línea muestra el promedio diario y la banda el mínimo–máximo de cada día.':'Se muestran las lecturas horarias individuales.';if(chart)chart.destroy();chart=new Chart($('chart'),{type:'line',data:{labels:display.labels,datasets:display.datasets},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},scales:{x:{ticks:{maxTicksLimit:9,callback(i){let raw=display.labels[i];return raw?new Date(raw.replace(' ','T')+(raw.length===10?'T00:00:00':'')).toLocaleDateString('es-CL'):''}},grid:{display:false}},y:{beginAtZero:true,title:{display:true,text:variable.unit}}},plugins:{legend:{display:display.daily,labels:{filter:item=>item.text!=='Mínimo diario'}},tooltip:{callbacks:{title(items){let raw=items[0].label;return raw.length===10?new Date(raw+'T00:00:00').toLocaleDateString('es-CL'):localDate(raw)}}}}}})}catch(error){console.error(error);$('chart-empty').hidden=false;$('chart-empty').textContent='No fue posible cargar los datos.'}}
async function downloadSelection(){let s=stations[selected],period=$('period').value;if(!confirm('Los datos son experimentales y no constituyen una medición regulatoria oficial. ¿Deseas descargarlos?'))return;let rows=await rowsFor(s,period);if(rows.length)save(`sensor-${s.sensor_id}-${s.environment}-${period}.csv`,new Blob(['\ufeff'+safeCsv(rows)],{type:'text/csv'}))}
async function downloadAll(){if(!confirm('Se generará un ZIP con un CSV independiente por sensor. Los datos son experimentales. ¿Deseas continuar?'))return;let button=$('download-all');button.disabled=true;try{let zip=new JSZip();for(let [i,s] of stations.entries()){button.textContent=`Preparando ${i+1}/${stations.length}…`;let rows=await rowsFor(s,'all');zip.file(`sensor-${s.sensor_id}-${s.environment}.csv`,'\ufeff'+safeCsv(rows))}save('aire_aysen_por_sensor.zip',await zip.generateAsync({type:'blob',compression:'DEFLATE'}))}finally{button.disabled=false;button.textContent='Descargar todos por sensor (.zip)'}}
async function checkUpdates(){try{let fresh=await fetch('data/manifest.json?v='+Date.now(),{cache:'no-store'}).then(r=>r.json());$('live-dot').style.background='#3bd2a2';$('live-label').textContent='Datos disponibles';if(fresh.updated_at!==manifest.updated_at){manifest=fresh;stations=fresh.stations;cache={};await loadLatest();fillSensors();render()}$('updated').textContent=localDate(manifest.updated_at)}catch(error){$('live-dot').style.background='#e7b94d';$('live-label').textContent='Última copia publicada'}}
async function loadLatest(){latest={};csv(await fetch('data/latest.csv?v='+Date.now(),{cache:'no-store'}).then(r=>r.text())).forEach(row=>latest[row.sensor_id]=row)}
async function init(){manifest=await fetch('data/manifest.json?v='+Date.now()).then(r=>r.json());stations=manifest.stations;await loadLatest();setupMap();selected=Math.max(0,stations.findIndex(s=>s.sensor_id===31));fillSensors();$('updated').textContent=localDate(manifest.updated_at);$('live-dot').style.background='#3bd2a2';$('live-label').textContent='Datos disponibles';render();setInterval(checkUpdates,600000)}
$('environment').onchange=()=>{fillSensors();render()};$('sensor').onchange=e=>{selected=stations.findIndex(s=>s.sensor_id===Number(e.target.value));render()};$('variable').onchange=render;$('period').onchange=render;$('download-selection').onclick=downloadSelection;$('download-all').onclick=downloadAll;init().catch(error=>{$('live-label').textContent='Datos no disponibles';console.error(error)});
